### ISSUE TITLE
(Not Issue)Power consumption of this hardware? 

### ISSUE THREAD

**Issue by maharshi114** [perja12/nexa_remote_control#1]
Hello, 
I appreciate you for this nice project. 
Can you share the following information for the reference only?

1. Battery Type?
2. Battery voltage range?
3. Current consumption in active mode?
4. Current consumption in sleep mode?
5. The total life of a battery?

**Comment by perja12** [comment]
Thanks!

The battery I use for this project is a CR2032 (f.ex. https://data.energizer.com/pdfs/cr2032.pdf) nominal voltage of 3.0V and capacity of 235 mAh.

The active current consumption when the circuit is transmitting is about 3.7 mA and the sleep current is around 0.17 uA. The total life of the battery depends on how much it is used and I haven't measured the average current consumption over a longer time when in use. But for me it has lasted for years already. The active period only lasts for 250 ms or so before it goes back to sleep.

**Comment by maharshi114** [comment]
Great.  Thank you for the quick replay.
